name: Build PR

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create git branch
        run: |
          # Create a git branch from the detached HEAD.
          # We need this for some integration tests.
          # This branch is not pushed, it's just local to the workflow environment.
          git checkout -b test-branch-${{ github.sha }}

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          cache: 'npm'

      - name: Set build version
        run: echo ::set-output name=TAG::0.0.0-${{ github.event_name == 'pull_request' && 'alpha' || 'beta' }}.$(git rev-parse --short HEAD)
        id: version

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        if: ${{ github.event_name == 'pull_request' }}
        id: find-comment-1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Your pull request has been published to npm

      - name: Update existing comment with stale state of npm release
        uses: peter-evans/create-or-update-comment@v1
        id: update-existing
        if: ${{ github.event_name == 'pull_request' && steps.find-comment-1.outputs.comment-id != '' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.find-comment-1.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            Your pull request has been published to npm.

            You can install it by running:

            ```
            npm install @xata.io/client@${{ steps.version.outputs.TAG }}
            npm install @xata.io/codegen@${{ steps.version.outputs.TAG }}
            npm install @xata.io/importer@${{ steps.version.outputs.TAG }}
            npm install @xata.io/shell@${{ steps.version.outputs.TAG }}
            ```

            [Pull request has been updated, please wait for latest changes to be pushed to npm...]

      - name: Install dependencies
        run: lerna bootstrap

      - name: Lint
        run: npm run lint

      - name: Compile
        run: npm run build

      - name: Test
        run: npm test
        env:
          XATA_DATABASE_URL: ${{ secrets.INTEGRATION_TEST_DATABASE_URL }}
          XATA_API_KEY: ${{ secrets.INTEGRATION_TEST_API_KEY }}
          XATA_DATABASE_BRANCH: ${{ secrets.INTEGRATION_TEST_BRANCH }}

      - name: Configure npm registry token
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish beta build
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: npx lerna publish ${{ steps.version.outputs.TAG }} --no-git-tag-version --no-push --dist-tag dev --no-verify-access --yes

      - name: Publish canary build
        if: ${{ github.event_name == 'pull_request' }}
        run: npx lerna publish ${{ steps.version.outputs.TAG }} --no-git-tag-version --no-push --dist-tag canary --no-verify-access --yes

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        if: ${{ github.event_name == 'pull_request' }}
        id: find-comment-2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Your pull request has been published to npm

      - name: Create or update comment of npm release
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.find-comment-2.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            Your pull request has been published to npm.

            You can install it by running:

            ```
            npm install @xata.io/client@${{ steps.version.outputs.TAG }}
            npm install @xata.io/codegen@${{ steps.version.outputs.TAG }}
            npm install @xata.io/importer@${{ steps.version.outputs.TAG }}
            npm install @xata.io/shell@${{ steps.version.outputs.TAG }}
            ```
